openapi: 3.0.2
info:
  title: umbraco-backoffice-api
  version: 1.0.0
paths:
  /init:
    get:
      operationId: GetInit
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitResponse'
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /version:
    get:
      operationId: GetVersion
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /install:
    get:
      operationId: GetInstall
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UmbracoInstaller'
    post:
      operationId: PostInstall
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UmbracoPerformInstallRequest'
        required: true
      responses:
        '201':
          description: 201 response
        '400':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /install/database/validate:
    post:
      operationId: PostInstallValidateDatabase
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UmbracoPerformInstallDatabaseConfiguration'
        required: true
      responses:
        '201':
          description: 201 response
        '400':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user:
    get:
      operationId: GetUser
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: 403 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user/login:
    post:
      operationId: PostUserLogin
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
        required: true
      responses:
        '201':
          description: 201 response
        '403':
          description: 403 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user/logout:
    post:
      operationId: PostUserLogout
      responses:
        '201':
          description: 201 response
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user/sections:
    get:
      operationId: GetAllowedSections
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllowedSectionsResponse'
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    InitResponse:
      type: object
      properties:
        installed:
          type: boolean
      required:
        - installed
    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
      required:
        - errorMessage
    VersionResponse:
      type: object
      properties:
        version:
          type: string
      required:
        - version
    ConsentLevel:
      type: string
      enum:
        - Minimal
        - Basic
        - Detailed
    TelemetryModel:
      type: object
      properties:
        level:
          $ref: '#/components/schemas/ConsentLevel'
        description:
          type: string
      required:
        - level
        - description
    UmbracoInstallerUserModel:
      type: object
      properties:
        minCharLength:
          type: number
          format: float
        minNonAlphaNumericLength:
          type: number
          format: float
        consentLevels:
          type: array
          items:
            $ref: '#/components/schemas/TelemetryModel'
      required:
        - minCharLength
        - minNonAlphaNumericLength
        - consentLevels
    UmbracoInstallerDatabaseModel:
      type: object
      properties:
        id:
          type: string
        sortOrder:
          type: number
          format: float
        displayName:
          type: string
        defaultDatabaseName:
          type: string
        providerName:
          type: string
          nullable: true
        isAvailable:
          type: boolean
        requiresServer:
          type: boolean
        serverPlaceholder:
          type: string
          nullable: true
        requiresCredentials:
          type: boolean
        supportsIntegratedAuthentication:
          type: boolean
        requiresConnectionTest:
          type: boolean
      required:
        - id
        - sortOrder
        - displayName
        - defaultDatabaseName
        - providerName
        - isAvailable
        - requiresServer
        - serverPlaceholder
        - requiresCredentials
        - supportsIntegratedAuthentication
        - requiresConnectionTest
    UmbracoInstaller:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UmbracoInstallerUserModel'
        databases:
          type: array
          items:
            $ref: '#/components/schemas/UmbracoInstallerDatabaseModel'
      required:
        - user
        - databases
    UmbracoPerformInstallDatabaseConfiguration:
      type: object
      properties:
        server:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        username:
          type: string
          nullable: true
        databaseName:
          type: string
          nullable: true
        databaseType:
          type: string
          nullable: true
        useIntegratedAuthentication:
          type: boolean
          nullable: true
        connectionString:
          type: string
          nullable: true
    UmbracoPerformInstallRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        subscribeToNewsletter:
          type: boolean
        telemetryLevel:
          $ref: '#/components/schemas/ConsentLevel'
        database:
          $ref: '#/components/schemas/UmbracoPerformInstallDatabaseConfiguration'
      required:
        - name
        - email
        - password
        - subscribeToNewsletter
        - telemetryLevel
        - database
    UserResponse:
      type: object
      properties:
        username:
          type: string
        role:
          type: string
      required:
        - username
        - role
    UserLoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        persist:
          type: boolean
      required:
        - username
        - password
        - persist
    AllowedSectionsResponse:
      type: object
      properties:
        sections:
          type: array
          items:
            type: string
      required:
        - sections
